version: '3.8'

services:
  app:
    build:
      context: .
    env_file:
      - .env.production
    depends_on:
      - mongo
    command: ["npm", "start"]  # Use the start script for production
  mongo:
    image: mongo:6.0
    container_name: mongo
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
