name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main # Replace with your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up SSH access
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

    # Step 3: Pull latest changes and deploy
    - name: Deploy updates
      run: |
          ssh -o StrictHostKeyChecking=no root@144.126.216.56 << 'EOF'
          cd /var/www/html/blogging-platform
          git reset --hard # Reset any uncommitted changes
          git pull origin main # Pull the latest changes
          /root/.nvm/versions/node/v22.11.0/bin/npm install # Install dependencies
          /root/.nvm/versions/node/v22.11.0/bin/npm run build # Build the app
          /root/.nvm/versions/node/v22.11.0/bin/pm2 restart nextjs-app || /root/.nvm/versions/node/v22.11.0/bin/pm2 start npm --name "nextjs-app" -- start
          EOF
