name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up SSH access
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

    # Step 3: Deploy application
    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no root@144.126.216.56 << 'EOF'
        export PATH="/root/.nvm/versions/node/v22.11.0/bin:$PATH"
        cd /var/www/html/blogging-platform
        git reset --hard
        git pull origin main
        npm install
        npm run build
        pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
        EOF